http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:                  # name, used as reference in pipeline
    host: '*'       # wildcard pattern support
    paths:
      - '/api/login'
      - '/api/signup'
  store:                  # name, used as reference in pipeline
    host: '*'       # wildcard pattern support
    paths:
      - '/api/movies'
serviceEndpoints:
  authApi:
    url: 'http://localhost:3000'
  storeApi:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
    - name: auth-public
      apiEndpoints:
        - api
      policies:
        # - jwt:
        #   - action:
        #       secretOrPublicKey: 'geheim'
        - cors:
          - action:
              origin: 'http://localhost:4200'
        - log: # policy name
          - action:    # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} # parameter for log action
        - proxy:
            - action:
                serviceEndpoint: authApi
    - name: store-private
      apiEndpoints:
        - store
      policies:
        - cors:
          - action:
              origin: 'http://localhost:4200'
        - log: # policy name
          - action:    # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} # parameter for log action
        - proxy:
            - action:
                serviceEndpoint: storeApi